### ISSUE TITLE
Loading endlessly in backend

### ISSUE THREAD

**Issue by dermansi** [sitegeist/translatelabels#14]
Hey,

thank you for providing this open source extension!

It is working fine - except the backend view (the one that opens in a new tab via ajax link when you click the edit links in admin panel) loads endlessly:

![image](https://user-images.githubusercontent.com/14231192/109316529-ff894a80-784b-11eb-85d2-8eca952bf285.png)

Editing the label directly in the frontend or directly in the backend works fine.

We are using an admin account and the access to the folder is given.  TYPO3 v10.4.13. Translate Labels 2.0.6

Do you have any suggestions or a potential solution for this problem?

Kind regards
Manuel

**Comment by galoppi** [comment]
Fixed in new version
