### ISSUE TITLE
Middleware namespace is wrong, throws errors in some installations

### ISSUE THREAD

**Issue by bisratK** [sitegeist/translatelabels#15]
`namespace Sitegeist\TranslateLabels\Middleware;` should be `namespace Sitegeist\Translatelabels\Middleware;` 
name space is not case sensitive, but composer is, there fore if the extension is installed by composer the following error is thrown.
`Class 'Sitegeist\Translatelabels\Middleware\CreateLabelResolver' not found`
This issue is also seen in version 10.

**Comment by galoppi** [comment]
Fixed in [2.0.8](https://github.com/sitegeist/translatelabels/releases/tag/2.0.8)
